dist: trusty

sudo: false

language: cpp

compiler:
    - gcc
    - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
            - clang
            - cppcheck
            - cmake
            - lcov
            - libssh2-1-dev
            - libsuitesparse-dev
            - libeigen3-dev


before_script:
    - ./travis/before_script.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST_BRANCH
    - ./travis/compile_g2o.sh

script:
    - ./travis/script.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST_BRANCH

after_script:
    - ./travis/after_script.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST_BRANCH
